version: '3.8'

services:
  api:
    build: ./server  
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app  
      - .env:/app/.env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
  client:
      build: ./client  
      ports:
        - "5173:5173"
      volumes:
        - ./client:/app  
        - /app/node_modules
      depends_on:
        - api
      environment:
        - WDS_SOCKET_PORT=5173 

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"
    depends_on:
      - db

volumes:
  postgres_data:
