version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - .env:/.env  # Monter le fichier .env
    depends_on:
      - db

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data 
      - ./migration/dump.sql:/docker-entrypoint-initdb.d/dump.sql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"
    depends_on:
      - db

volumes:
  postgres_data: