version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  # Montez le fichier de configuration Nginx en lecture seule dans le conteneur Nginx
      - .env:/app/.env
    environment:
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: db
      DB_PORT: ${DB_PORT}
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migration/dump.sql:/docker-entrypoint-initdb.d/dump.sql:ro
    networks:
      - mynetwork

  adminer:
    image: adminer
    restart: always
    ports:
      - "8282:8080"
    depends_on:
      - db
    networks:
      - mynetwork

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro  
    restart: always
    ports:
      - "8080:80"
    depends_on:
      - api
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge

volumes:
  postgres_data:
