name: Build and Push Docker Images to Docker Hub

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Build and push the 'server' (API) image
    - name: Build and push server Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/server-image:${{ github.sha }} ./server
        docker push ${{ secrets.DOCKER_USERNAME }}/server-image:${{ github.sha }}

    # Build and push the 'client' image
    - name: Build and push client Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/client-image:${{ github.sha }} ./client
        docker push ${{ secrets.DOCKER_USERNAME }}/client-image:${{ github.sha }}

    - name: Log out from Docker Hub
      run: docker logout
